# Generated by Django 2.2.2 on 2019-07-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oist',
            new_name='Post',
        ),
    ]
